//https://dummyjson.com/products/category-list
//https://dummyjson.com/products/category/tablets

[
  {
    id: 121,
    title: 'iPhone 5s',
    description:
      "The iPhone 5s is a classic smartphone known for its compact design and advanced features during its release. While it's an older model, it still provides a reliable user experience.",
    category: 'smartphones',
    price: 199.99,
    discountPercentage: 11.85,
    rating: 3.92,
    stock: 65,
    tags: ['smartphones', 'apple'],
    brand: 'Apple',
    sku: 'AZ1L68SM',
    weight: 4,
    dimensions: {
      width: 8.49,
      height: 25.34,
      depth: 18.12,
    },
    warrantyInformation: '1 week warranty',
    shippingInformation: 'Ships in 1 week',
    availabilityStatus: 'In Stock',
    reviews: [
      {
        rating: 4,
        comment: 'Highly impressed!',
        date: '2024-05-23T08:56:21.625Z',
        reviewerName: 'Wyatt Perry',
        reviewerEmail: 'wyatt.perry@x.dummyjson.com',
      },
      {
        rating: 5,
        comment: 'Awesome product!',
        date: '2024-05-23T08:56:21.625Z',
        reviewerName: 'Olivia Anderson',
        reviewerEmail: 'olivia.anderson@x.dummyjson.com',
      },
      {
        rating: 4,
        comment: 'Highly recommended!',
        date: '2024-05-23T08:56:21.625Z',
        reviewerName: 'Mateo Nguyen',
        reviewerEmail: 'mateo.nguyen@x.dummyjson.com',
      },
    ],
    returnPolicy: 'No return policy',
    minimumOrderQuantity: 2,
    meta: {
      createdAt: '2024-05-23T08:56:21.625Z',
      updatedAt: '2024-05-23T08:56:21.625Z',
      barcode: '2903942810911',
      qrCode: 'https://assets.dummyjson.com/public/qr-code.png',
    },
    images: [
      'https://cdn.dummyjson.com/products/images/smartphones/iPhone%205s/1.png',
      'https://cdn.dummyjson.com/products/images/smartphones/iPhone%205s/2.png',
      'https://cdn.dummyjson.com/products/images/smartphones/iPhone%205s/3.png',
    ],
    thumbnail:
      'https://cdn.dummyjson.com/products/images/smartphones/iPhone%205s/thumbnail.png',
  },
  {
    id: 122,
    title: 'iPhone 6',
    description:
      'The iPhone 6 is a stylish and capable smartphone with a larger display and improved performance. It introduced new features and design elements, making it a popular choice in its time.',
    category: 'smartphones',
    price: 299.99,
    discountPercentage: 4.54,
    rating: 3.76,
    stock: 99,
    tags: ['smartphones', 'apple'],
    brand: 'Apple',
    sku: 'ZPXH3X9J',
    weight: 8,
    dimensions: {
      width: 16.21,
      height: 22.94,
      depth: 5.63,
    },
    warrantyInformation: '3 year warranty',
    shippingInformation: 'Ships overnight',
    availabilityStatus: 'In Stock',
    reviews: [
      {
        rating: 5,
        comment: 'Would buy again!',
        date: '2024-05-23T08:56:21.625Z',
        reviewerName: 'Nicholas Bailey',
        reviewerEmail: 'nicholas.bailey@x.dummyjson.com',
      },
      {
        rating: 5,
        comment: 'Great product!',
        date: '2024-05-23T08:56:21.625Z',
        reviewerName: 'Clara Berry',
        reviewerEmail: 'clara.berry@x.dummyjson.com',
      },
      {
        rating: 3,
        comment: 'Not as described!',
        date: '2024-05-23T08:56:21.625Z',
        reviewerName: 'Gavin Stanley',
        reviewerEmail: 'gavin.stanley@x.dummyjson.com',
      },
    ],
    returnPolicy: '60 days return policy',
    minimumOrderQuantity: 3,
    meta: {
      createdAt: '2024-05-23T08:56:21.625Z',
      updatedAt: '2024-05-23T08:56:21.625Z',
      barcode: '2517230562429',
      qrCode: 'https://assets.dummyjson.com/public/qr-code.png',
    },
    images: [
      'https://cdn.dummyjson.com/products/images/smartphones/iPhone%206/1.png',
      'https://cdn.dummyjson.com/products/images/smartphones/iPhone%206/2.png',
      'https://cdn.dummyjson.com/products/images/smartphones/iPhone%206/3.png',
    ],
    thumbnail:
      'https://cdn.dummyjson.com/products/images/smartphones/iPhone%206/thumbnail.png',
  },
  {
    id: 123,
    title: 'iPhone 13 Pro',
    description:
      'The iPhone 13 Pro is a cutting-edge smartphone with a powerful camera system, high-performance chip, and stunning display. It offers advanced features for users who demand top-notch technology.',
    category: 'smartphones',
    price: 1099.99,
    discountPercentage: 18.3,
    rating: 3.42,
    stock: 26,
    tags: ['smartphones', 'apple'],
    brand: 'Apple',
    sku: 'YGQKHPGK',
    weight: 8,
    dimensions: {
      width: 22.39,
      height: 9.77,
      depth: 19.6,
    },
    warrantyInformation: '1 year warranty',
    shippingInformation: 'Ships in 2 weeks',
    availabilityStatus: 'In Stock',
    reviews: [
      {
        rating: 5,
        comment: 'Highly impressed!',
        date: '2024-05-23T08:56:21.625Z',
        reviewerName: 'Aria Roberts',
        reviewerEmail: 'aria.roberts@x.dummyjson.com',
      },
      {
        rating: 4,
        comment: 'Great product!',
        date: '2024-05-23T08:56:21.625Z',
        reviewerName: 'Ryan Graham',
        reviewerEmail: 'ryan.graham@x.dummyjson.com',
      },
      {
        rating: 2,
        comment: 'Poor quality!',
        date: '2024-05-23T08:56:21.625Z',
        reviewerName: 'Mason Wright',
        reviewerEmail: 'mason.wright@x.dummyjson.com',
      },
    ],
    returnPolicy: '7 days return policy',
    minimumOrderQuantity: 1,
    meta: {
      createdAt: '2024-05-23T08:56:21.625Z',
      updatedAt: '2024-05-23T08:56:21.625Z',
      barcode: '2986724589988',
      qrCode: 'https://assets.dummyjson.com/public/qr-code.png',
    },
    images: [
      'https://cdn.dummyjson.com/products/images/smartphones/iPhone%2013%20Pro/1.png',
      'https://cdn.dummyjson.com/products/images/smartphones/iPhone%2013%20Pro/2.png',
      'https://cdn.dummyjson.com/products/images/smartphones/iPhone%2013%20Pro/3.png',
    ],
    thumbnail:
      'https://cdn.dummyjson.com/products/images/smartphones/iPhone%2013%20Pro/thumbnail.png',
  },
  {
    id: 124,
    title: 'iPhone X',
    description:
      'The iPhone X is a flagship smartphone featuring a bezel-less OLED display, facial recognition technology (Face ID), and impressive performance. It represents a milestone in iPhone design and innovation.',
    category: 'smartphones',
    price: 899.99,
    discountPercentage: 14.19,
    rating: 4.96,
    stock: 99,
    tags: ['smartphones', 'apple'],
    brand: 'Apple',
    sku: '9QN3UDUD',
    weight: 10,
    dimensions: {
      width: 27.86,
      height: 8.53,
      depth: 17.07,
    },
    warrantyInformation: '3 months warranty',
    shippingInformation: 'Ships in 1 month',
    availabilityStatus: 'In Stock',
    reviews: [
      {
        rating: 1,
        comment: 'Very unhappy with my purchase!',
        date: '2024-05-23T08:56:21.625Z',
        reviewerName: 'Eleanor Tyler',
        reviewerEmail: 'eleanor.tyler@x.dummyjson.com',
      },
      {
        rating: 5,
        comment: 'Very satisfied!',
        date: '2024-05-23T08:56:21.625Z',
        reviewerName: 'Maya Reed',
        reviewerEmail: 'maya.reed@x.dummyjson.com',
      },
      {
        rating: 4,
        comment: 'Fast shipping!',
        date: '2024-05-23T08:56:21.625Z',
        reviewerName: 'Elena Baker',
        reviewerEmail: 'elena.baker@x.dummyjson.com',
      },
    ],
    returnPolicy: '30 days return policy',
    minimumOrderQuantity: 2,
    meta: {
      createdAt: '2024-05-23T08:56:21.625Z',
      updatedAt: '2024-05-23T08:56:21.625Z',
      barcode: '4331405454760',
      qrCode: 'https://assets.dummyjson.com/public/qr-code.png',
    },
    images: [
      'https://cdn.dummyjson.com/products/images/smartphones/iPhone%20X/1.png',
      'https://cdn.dummyjson.com/products/images/smartphones/iPhone%20X/2.png',
      'https://cdn.dummyjson.com/products/images/smartphones/iPhone%20X/3.png',
    ],
    thumbnail:
      'https://cdn.dummyjson.com/products/images/smartphones/iPhone%20X/thumbnail.png',
  },
  {
    id: 78,
    title: 'Apple MacBook Pro 14 Inch Space Grey',
    description:
      "The MacBook Pro 14 Inch in Space Grey is a powerful and sleek laptop, featuring Apple's M1 Pro chip for exceptional performance and a stunning Retina display.",
    category: 'laptops',
    price: 1999.99,
    discountPercentage: 9.25,
    rating: 3.13,
    stock: 39,
    tags: ['laptops', 'apple'],
    brand: 'Apple',
    sku: 'QDKO6NRJ',
    weight: 4,
    dimensions: {
      width: 12.38,
      height: 21.55,
      depth: 27.95,
    },
    warrantyInformation: '1 month warranty',
    shippingInformation: 'Ships in 1 week',
    availabilityStatus: 'In Stock',
    reviews: [
      {
        rating: 5,
        comment: 'Would buy again!',
        date: '2024-05-23T08:56:21.622Z',
        reviewerName: 'Hunter Gordon',
        reviewerEmail: 'hunter.gordon@x.dummyjson.com',
      },
      {
        rating: 5,
        comment: 'Would buy again!',
        date: '2024-05-23T08:56:21.622Z',
        reviewerName: 'Emma Wilson',
        reviewerEmail: 'emma.wilson@x.dummyjson.com',
      },
      {
        rating: 5,
        comment: 'Very pleased!',
        date: '2024-05-23T08:56:21.622Z',
        reviewerName: 'David Martinez',
        reviewerEmail: 'david.martinez@x.dummyjson.com',
      },
    ],
    returnPolicy: '30 days return policy',
    minimumOrderQuantity: 1,
    meta: {
      createdAt: '2024-05-23T08:56:21.622Z',
      updatedAt: '2024-05-23T08:56:21.622Z',
      barcode: '3883623063065',
      qrCode: 'https://assets.dummyjson.com/public/qr-code.png',
    },
    images: [
      'https://cdn.dummyjson.com/products/images/laptops/Apple%20MacBook%20Pro%2014%20Inch%20Space%20Grey/1.png',
      'https://cdn.dummyjson.com/products/images/laptops/Apple%20MacBook%20Pro%2014%20Inch%20Space%20Grey/2.png',
      'https://cdn.dummyjson.com/products/images/laptops/Apple%20MacBook%20Pro%2014%20Inch%20Space%20Grey/3.png',
    ],
    thumbnail:
      'https://cdn.dummyjson.com/products/images/laptops/Apple%20MacBook%20Pro%2014%20Inch%20Space%20Grey/thumbnail.png',
  },
  {
    id: 79,
    title: 'Asus Zenbook Pro Dual Screen Laptop',
    description:
      'The Asus Zenbook Pro Dual Screen Laptop is a high-performance device with dual screens, providing productivity and versatility for creative professionals.',
    category: 'laptops',
    price: 1799.99,
    discountPercentage: 9.21,
    rating: 3.14,
    stock: 38,
    tags: ['laptops'],
    brand: 'Asus',
    sku: '4A9KFMBG',
    weight: 8,
    dimensions: {
      width: 19.67,
      height: 11.05,
      depth: 14.32,
    },
    warrantyInformation: 'No warranty',
    shippingInformation: 'Ships in 3-5 business days',
    availabilityStatus: 'In Stock',
    reviews: [
      {
        rating: 5,
        comment: 'Very satisfied!',
        date: '2024-05-23T08:56:21.622Z',
        reviewerName: 'Jack Ward',
        reviewerEmail: 'jack.ward@x.dummyjson.com',
      },
      {
        rating: 1,
        comment: 'Very disappointed!',
        date: '2024-05-23T08:56:21.622Z',
        reviewerName: 'Ava Harris',
        reviewerEmail: 'ava.harris@x.dummyjson.com',
      },
      {
        rating: 5,
        comment: 'Great value for money!',
        date: '2024-05-23T08:56:21.622Z',
        reviewerName: 'Brayden Fleming',
        reviewerEmail: 'brayden.fleming@x.dummyjson.com',
      },
    ],
    returnPolicy: 'No return policy',
    minimumOrderQuantity: 1,
    meta: {
      createdAt: '2024-05-23T08:56:21.622Z',
      updatedAt: '2024-05-23T08:56:21.622Z',
      barcode: '2899455033799',
      qrCode: 'https://assets.dummyjson.com/public/qr-code.png',
    },
    images: [
      'https://cdn.dummyjson.com/products/images/laptops/Asus%20Zenbook%20Pro%20Dual%20Screen%20Laptop/1.png',
      'https://cdn.dummyjson.com/products/images/laptops/Asus%20Zenbook%20Pro%20Dual%20Screen%20Laptop/2.png',
      'https://cdn.dummyjson.com/products/images/laptops/Asus%20Zenbook%20Pro%20Dual%20Screen%20Laptop/3.png',
    ],
    thumbnail:
      'https://cdn.dummyjson.com/products/images/laptops/Asus%20Zenbook%20Pro%20Dual%20Screen%20Laptop/thumbnail.png',
  },
  {
    id: 80,
    title: 'Huawei Matebook X Pro',
    description:
      'The Huawei Matebook X Pro is a slim and stylish laptop with a high-resolution touchscreen display, offering a premium experience for users on the go.',
    category: 'laptops',
    price: 1399.99,
    discountPercentage: 15.25,
    rating: 4.62,
    stock: 34,
    tags: ['laptops'],
    brand: 'Huawei',
    sku: 'U2CBNNB0',
    weight: 9,
    dimensions: {
      width: 22.11,
      height: 11.11,
      depth: 23.07,
    },
    warrantyInformation: '2 year warranty',
    shippingInformation: 'Ships in 2 weeks',
    availabilityStatus: 'In Stock',
    reviews: [
      {
        rating: 4,
        comment: 'Great value for money!',
        date: '2024-05-23T08:56:21.622Z',
        reviewerName: 'Samantha Howard',
        reviewerEmail: 'samantha.howard@x.dummyjson.com',
      },
      {
        rating: 2,
        comment: 'Would not buy again!',
        date: '2024-05-23T08:56:21.622Z',
        reviewerName: 'Daniel Cook',
        reviewerEmail: 'daniel.cook@x.dummyjson.com',
      },
      {
        rating: 5,
        comment: 'Very satisfied!',
        date: '2024-05-23T08:56:21.622Z',
        reviewerName: 'Brayden Fleming',
        reviewerEmail: 'brayden.fleming@x.dummyjson.com',
      },
    ],
    returnPolicy: '60 days return policy',
    minimumOrderQuantity: 1,
    meta: {
      createdAt: '2024-05-23T08:56:21.622Z',
      updatedAt: '2024-05-23T08:56:21.622Z',
      barcode: '1232723732298',
      qrCode: 'https://assets.dummyjson.com/public/qr-code.png',
    },
    images: [
      'https://cdn.dummyjson.com/products/images/laptops/Huawei%20Matebook%20X%20Pro/1.png',
      'https://cdn.dummyjson.com/products/images/laptops/Huawei%20Matebook%20X%20Pro/2.png',
      'https://cdn.dummyjson.com/products/images/laptops/Huawei%20Matebook%20X%20Pro/3.png',
    ],
    thumbnail:
      'https://cdn.dummyjson.com/products/images/laptops/Huawei%20Matebook%20X%20Pro/thumbnail.png',
  },
  {
    id: 81,
    title: 'Lenovo Yoga 920',
    description:
      'The Lenovo Yoga 920 is a 2-in-1 convertible laptop with a flexible hinge, allowing you to use it as a laptop or tablet, offering versatility and portability.',
    category: 'laptops',
    price: 1099.99,
    discountPercentage: 7.77,
    rating: 2.98,
    stock: 71,
    tags: ['laptops'],
    brand: 'Lenovo',
    sku: 'MST9WZQY',
    weight: 7,
    dimensions: {
      width: 11.02,
      height: 14.45,
      depth: 24.09,
    },
    warrantyInformation: 'Lifetime warranty',
    shippingInformation: 'Ships in 1 week',
    availabilityStatus: 'In Stock',
    reviews: [
      {
        rating: 4,
        comment: 'Very happy with my purchase!',
        date: '2024-05-23T08:56:21.623Z',
        reviewerName: 'Paisley Bell',
        reviewerEmail: 'paisley.bell@x.dummyjson.com',
      },
      {
        rating: 4,
        comment: 'Very pleased!',
        date: '2024-05-23T08:56:21.623Z',
        reviewerName: 'Lincoln Kelly',
        reviewerEmail: 'lincoln.kelly@x.dummyjson.com',
      },
      {
        rating: 4,
        comment: 'Great product!',
        date: '2024-05-23T08:56:21.623Z',
        reviewerName: 'Luna Russell',
        reviewerEmail: 'luna.russell@x.dummyjson.com',
      },
    ],
    returnPolicy: 'No return policy',
    minimumOrderQuantity: 1,
    meta: {
      createdAt: '2024-05-23T08:56:21.623Z',
      updatedAt: '2024-05-23T08:56:21.623Z',
      barcode: '9590995785298',
      qrCode: 'https://assets.dummyjson.com/public/qr-code.png',
    },
    images: [
      'https://cdn.dummyjson.com/products/images/laptops/Lenovo%20Yoga%20920/1.png',
      'https://cdn.dummyjson.com/products/images/laptops/Lenovo%20Yoga%20920/2.png',
      'https://cdn.dummyjson.com/products/images/laptops/Lenovo%20Yoga%20920/3.png',
    ],
    thumbnail:
      'https://cdn.dummyjson.com/products/images/laptops/Lenovo%20Yoga%20920/thumbnail.png',
  },
  {
    id: 82,
    title: 'New DELL XPS 13 9300 Laptop',
    description:
      'The New DELL XPS 13 9300 Laptop is a compact and powerful device, featuring a virtually borderless InfinityEdge display and high-end performance for various tasks.',
    category: 'laptops',
    price: 1499.99,
    discountPercentage: 11.7,
    rating: 2.98,
    stock: 18,
    tags: ['laptops'],
    brand: 'Dell',
    sku: 'XBJJ446X',
    weight: 10,
    dimensions: {
      width: 12.09,
      height: 6.43,
      depth: 15.69,
    },
    warrantyInformation: 'Lifetime warranty',
    shippingInformation: 'Ships overnight',
    availabilityStatus: 'In Stock',
    reviews: [
      {
        rating: 3,
        comment: 'Very disappointed!',
        date: '2024-05-23T08:56:21.623Z',
        reviewerName: 'Julian Newton',
        reviewerEmail: 'julian.newton@x.dummyjson.com',
      },
      {
        rating: 4,
        comment: 'Very pleased!',
        date: '2024-05-23T08:56:21.623Z',
        reviewerName: 'Grace Perry',
        reviewerEmail: 'grace.perry@x.dummyjson.com',
      },
      {
        rating: 5,
        comment: 'Great product!',
        date: '2024-05-23T08:56:21.623Z',
        reviewerName: 'Daniel Taylor',
        reviewerEmail: 'daniel.taylor@x.dummyjson.com',
      },
    ],
    returnPolicy: '7 days return policy',
    minimumOrderQuantity: 1,
    meta: {
      createdAt: '2024-05-23T08:56:21.623Z',
      updatedAt: '2024-05-23T08:56:21.623Z',
      barcode: '0358629687929',
      qrCode: 'https://assets.dummyjson.com/public/qr-code.png',
    },
    images: [
      'https://cdn.dummyjson.com/products/images/laptops/New%20DELL%20XPS%2013%209300%20Laptop/1.png',
      'https://cdn.dummyjson.com/products/images/laptops/New%20DELL%20XPS%2013%209300%20Laptop/2.png',
      'https://cdn.dummyjson.com/products/images/laptops/New%20DELL%20XPS%2013%209300%20Laptop/3.png',
    ],
    thumbnail:
      'https://cdn.dummyjson.com/products/images/laptops/New%20DELL%20XPS%2013%209300%20Laptop/thumbnail.png',
  },
  {
    id: 99,
    title: 'Amazon Echo Plus',
    description:
      'The Amazon Echo Plus is a smart speaker with built-in Alexa voice control. It features premium sound quality and serves as a hub for controlling smart home devices.',
    category: 'mobile-accessories',
    price: 99.99,
    discountPercentage: 16.3,
    rating: 3.52,
    stock: 50,
    tags: ['electronics', 'smart speakers'],
    brand: 'Amazon',
    sku: 'YHLK4W9V',
    weight: 7,
    dimensions: {
      width: 8.1,
      height: 7.74,
      depth: 5.68,
    },
    warrantyInformation: '1 month warranty',
    shippingInformation: 'Ships in 1 week',
    availabilityStatus: 'In Stock',
    reviews: [
      {
        rating: 4,
        comment: 'Highly recommended!',
        date: '2024-05-23T08:56:21.624Z',
        reviewerName: 'Nora Mills',
        reviewerEmail: 'nora.mills@x.dummyjson.com',
      },
      {
        rating: 4,
        comment: 'Fast shipping!',
        date: '2024-05-23T08:56:21.624Z',
        reviewerName: 'Ava Taylor',
        reviewerEmail: 'ava.taylor@x.dummyjson.com',
      },
      {
        rating: 4,
        comment: 'Very pleased!',
        date: '2024-05-23T08:56:21.624Z',
        reviewerName: 'Aria Flores',
        reviewerEmail: 'aria.flores@x.dummyjson.com',
      },
    ],
    returnPolicy: '90 days return policy',
    minimumOrderQuantity: 1,
    meta: {
      createdAt: '2024-05-23T08:56:21.624Z',
      updatedAt: '2024-05-23T08:56:21.624Z',
      barcode: '0697313083842',
      qrCode: 'https://assets.dummyjson.com/public/qr-code.png',
    },
    images: [
      'https://cdn.dummyjson.com/products/images/mobile-accessories/Amazon%20Echo%20Plus/1.png',
      'https://cdn.dummyjson.com/products/images/mobile-accessories/Amazon%20Echo%20Plus/2.png',
    ],
    thumbnail:
      'https://cdn.dummyjson.com/products/images/mobile-accessories/Amazon%20Echo%20Plus/thumbnail.png',
  },
  {
    id: 100,
    title: 'Apple Airpods',
    description:
      'The Apple Airpods offer a seamless wireless audio experience. With easy pairing, high-quality sound, and Siri integration, they are perfect for on-the-go listening.',
    category: 'mobile-accessories',
    price: 129.99,
    discountPercentage: 4.82,
    rating: 4.38,
    stock: 93,
    tags: ['electronics', 'wireless earphones'],
    brand: 'Apple',
    sku: 'H76W8TSP',
    weight: 3,
    dimensions: {
      width: 22.62,
      height: 9.92,
      depth: 18.15,
    },
    warrantyInformation: 'No warranty',
    shippingInformation: 'Ships in 3-5 business days',
    availabilityStatus: 'In Stock',
    reviews: [
      {
        rating: 3,
        comment: 'Waste of money!',
        date: '2024-05-23T08:56:21.624Z',
        reviewerName: 'Aaliyah Hanson',
        reviewerEmail: 'aaliyah.hanson@x.dummyjson.com',
      },
      {
        rating: 2,
        comment: 'Waste of money!',
        date: '2024-05-23T08:56:21.624Z',
        reviewerName: 'Leah Gutierrez',
        reviewerEmail: 'leah.gutierrez@x.dummyjson.com',
      },
      {
        rating: 3,
        comment: 'Not worth the price!',
        date: '2024-05-23T08:56:21.624Z',
        reviewerName: 'Jace Smith',
        reviewerEmail: 'jace.smith@x.dummyjson.com',
      },
    ],
    returnPolicy: '60 days return policy',
    minimumOrderQuantity: 3,
    meta: {
      createdAt: '2024-05-23T08:56:21.624Z',
      updatedAt: '2024-05-23T08:56:21.624Z',
      barcode: '3925144121840',
      qrCode: 'https://assets.dummyjson.com/public/qr-code.png',
    },
    images: [
      'https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20Airpods/1.png',
      'https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20Airpods/2.png',
      'https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20Airpods/3.png',
    ],
    thumbnail:
      'https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20Airpods/thumbnail.png',
  },
  {
    id: 101,
    title: 'Apple AirPods Max Silver',
    description:
      'The Apple AirPods Max in Silver are premium over-ear headphones with high-fidelity audio, adaptive EQ, and active noise cancellation. Experience immersive sound in style.',
    category: 'mobile-accessories',
    price: 549.99,
    discountPercentage: 11.7,
    rating: 3.11,
    stock: 7,
    tags: ['electronics', 'over-ear headphones'],
    brand: 'Apple',
    sku: 'HPK82VDE',
    weight: 4,
    dimensions: {
      width: 7.73,
      height: 18.36,
      depth: 17.87,
    },
    warrantyInformation: '3 months warranty',
    shippingInformation: 'Ships in 1 month',
    availabilityStatus: 'In Stock',
    reviews: [
      {
        rating: 1,
        comment: 'Waste of money!',
        date: '2024-05-23T08:56:21.624Z',
        reviewerName: 'Harper Kelly',
        reviewerEmail: 'harper.kelly@x.dummyjson.com',
      },
      {
        rating: 3,
        comment: 'Not as described!',
        date: '2024-05-23T08:56:21.624Z',
        reviewerName: 'Abigail Rivera',
        reviewerEmail: 'abigail.rivera@x.dummyjson.com',
      },
      {
        rating: 5,
        comment: 'Excellent quality!',
        date: '2024-05-23T08:56:21.624Z',
        reviewerName: 'Nora Russell',
        reviewerEmail: 'nora.russell@x.dummyjson.com',
      },
    ],
    returnPolicy: '90 days return policy',
    minimumOrderQuantity: 2,
    meta: {
      createdAt: '2024-05-23T08:56:21.624Z',
      updatedAt: '2024-05-23T08:56:21.624Z',
      barcode: '9261269777547',
      qrCode: 'https://assets.dummyjson.com/public/qr-code.png',
    },
    images: [
      'https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20AirPods%20Max%20Silver/1.png',
    ],
    thumbnail:
      'https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20AirPods%20Max%20Silver/thumbnail.png',
  },
  {
    id: 102,
    title: 'Apple Airpower Wireless Charger',
    description:
      'The Apple AirPower Wireless Charger provides a convenient way to charge your compatible Apple devices wirelessly. Simply place your devices on the charging mat for effortless charging.',
    category: 'mobile-accessories',
    price: 79.99,
    discountPercentage: 6.54,
    rating: 4.51,
    stock: 78,
    tags: ['electronics', 'wireless chargers'],
    brand: 'Apple',
    sku: 'CBIU3PMZ',
    weight: 3,
    dimensions: {
      width: 25.51,
      height: 20.44,
      depth: 26.48,
    },
    warrantyInformation: 'Lifetime warranty',
    shippingInformation: 'Ships in 1 month',
    availabilityStatus: 'In Stock',
    reviews: [
      {
        rating: 5,
        comment: 'Awesome product!',
        date: '2024-05-23T08:56:21.624Z',
        reviewerName: 'Bella Gonzalez',
        reviewerEmail: 'bella.gonzalez@x.dummyjson.com',
      },
      {
        rating: 4,
        comment: 'Very pleased!',
        date: '2024-05-23T08:56:21.624Z',
        reviewerName: 'Eli Bennett',
        reviewerEmail: 'eli.bennett@x.dummyjson.com',
      },
      {
        rating: 5,
        comment: 'Very pleased!',
        date: '2024-05-23T08:56:21.624Z',
        reviewerName: 'Cameron Perez',
        reviewerEmail: 'cameron.perez@x.dummyjson.com',
      },
    ],
    returnPolicy: '7 days return policy',
    minimumOrderQuantity: 8,
    meta: {
      createdAt: '2024-05-23T08:56:21.624Z',
      updatedAt: '2024-05-23T08:56:21.624Z',
      barcode: '6981066059882',
      qrCode: 'https://assets.dummyjson.com/public/qr-code.png',
    },
    images: [
      'https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20Airpower%20Wireless%20Charger/1.png',
    ],
    thumbnail:
      'https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20Airpower%20Wireless%20Charger/thumbnail.png',
  },
  {
    id: 159,
    title: 'iPad Mini 2021 Starlight',
    description:
      'The iPad Mini 2021 in Starlight is a compact and powerful tablet from Apple. Featuring a stunning Retina display, powerful A-series chip, and a sleek design, it offers a premium tablet experience.',
    category: 'tablets',
    price: 499.99,
    discountPercentage: 19.48,
    rating: 3.87,
    stock: 32,
    tags: ['electronics', 'tablets'],
    brand: 'Apple',
    sku: 'L5CSWLNS',
    weight: 3,
    dimensions: {
      width: 24.9,
      height: 11.83,
      depth: 17.08,
    },
    warrantyInformation: '3 months warranty',
    shippingInformation: 'Ships in 2 weeks',
    availabilityStatus: 'In Stock',
    reviews: [
      {
        rating: 2,
        comment: 'Disappointing product!',
        date: '2024-05-23T08:56:21.626Z',
        reviewerName: 'Hazel Evans',
        reviewerEmail: 'hazel.evans@x.dummyjson.com',
      },
      {
        rating: 4,
        comment: 'Great product!',
        date: '2024-05-23T08:56:21.626Z',
        reviewerName: 'Sophia Jones',
        reviewerEmail: 'sophia.jones@x.dummyjson.com',
      },
      {
        rating: 5,
        comment: 'Great product!',
        date: '2024-05-23T08:56:21.626Z',
        reviewerName: 'Abigail Rivera',
        reviewerEmail: 'abigail.rivera@x.dummyjson.com',
      },
    ],
    returnPolicy: 'No return policy',
    minimumOrderQuantity: 3,
    meta: {
      createdAt: '2024-05-23T08:56:21.626Z',
      updatedAt: '2024-05-23T08:56:21.626Z',
      barcode: '6190943900668',
      qrCode: 'https://assets.dummyjson.com/public/qr-code.png',
    },
    images: [
      'https://cdn.dummyjson.com/products/images/tablets/iPad%20Mini%202021%20Starlight/1.png',
      'https://cdn.dummyjson.com/products/images/tablets/iPad%20Mini%202021%20Starlight/2.png',
      'https://cdn.dummyjson.com/products/images/tablets/iPad%20Mini%202021%20Starlight/3.png',
      'https://cdn.dummyjson.com/products/images/tablets/iPad%20Mini%202021%20Starlight/4.png',
    ],
    thumbnail:
      'https://cdn.dummyjson.com/products/images/tablets/iPad%20Mini%202021%20Starlight/thumbnail.png',
  },
  {
    id: 160,
    title: 'Samsung Galaxy Tab S8 Plus Grey',
    description:
      "The Samsung Galaxy Tab S8 Plus in Grey is a high-performance Android tablet by Samsung. With a large AMOLED display, powerful processor, and S Pen support, it's ideal for productivity and entertainment.",
    category: 'tablets',
    price: 599.99,
    discountPercentage: 8.11,
    rating: 3.43,
    stock: 76,
    tags: ['electronics', 'tablets'],
    brand: 'Samsung',
    sku: '1SIVLPFN',
    weight: 10,
    dimensions: {
      width: 18.5,
      height: 24.49,
      depth: 10.45,
    },
    warrantyInformation: '6 months warranty',
    shippingInformation: 'Ships in 1-2 business days',
    availabilityStatus: 'In Stock',
    reviews: [
      {
        rating: 2,
        comment: 'Would not buy again!',
        date: '2024-05-23T08:56:21.626Z',
        reviewerName: 'Jackson Morales',
        reviewerEmail: 'jackson.morales@x.dummyjson.com',
      },
      {
        rating: 5,
        comment: 'Would buy again!',
        date: '2024-05-23T08:56:21.626Z',
        reviewerName: 'Cameron Perez',
        reviewerEmail: 'cameron.perez@x.dummyjson.com',
      },
      {
        rating: 5,
        comment: 'Fast shipping!',
        date: '2024-05-23T08:56:21.626Z',
        reviewerName: 'Nova Cooper',
        reviewerEmail: 'nova.cooper@x.dummyjson.com',
      },
    ],
    returnPolicy: '30 days return policy',
    minimumOrderQuantity: 1,
    meta: {
      createdAt: '2024-05-23T08:56:21.626Z',
      updatedAt: '2024-05-23T08:56:21.626Z',
      barcode: '7204800760083',
      qrCode: 'https://assets.dummyjson.com/public/qr-code.png',
    },
    images: [
      'https://cdn.dummyjson.com/products/images/tablets/Samsung%20Galaxy%20Tab%20S8%20Plus%20Grey/1.png',
      'https://cdn.dummyjson.com/products/images/tablets/Samsung%20Galaxy%20Tab%20S8%20Plus%20Grey/2.png',
      'https://cdn.dummyjson.com/products/images/tablets/Samsung%20Galaxy%20Tab%20S8%20Plus%20Grey/3.png',
      'https://cdn.dummyjson.com/products/images/tablets/Samsung%20Galaxy%20Tab%20S8%20Plus%20Grey/4.png',
    ],
    thumbnail:
      'https://cdn.dummyjson.com/products/images/tablets/Samsung%20Galaxy%20Tab%20S8%20Plus%20Grey/thumbnail.png',
  },
  {
    id: 161,
    title: 'Samsung Galaxy Tab White',
    description:
      'The Samsung Galaxy Tab in White is a sleek and versatile Android tablet. With a vibrant display, long-lasting battery, and a range of features, it offers a great user experience for various tasks.',
    category: 'tablets',
    price: 349.99,
    discountPercentage: 4.82,
    rating: 3.7,
    stock: 0,
    tags: ['electronics', 'tablets'],
    brand: 'Samsung',
    sku: 'AKJPAPFO',
    weight: 8,
    dimensions: {
      width: 12.42,
      height: 10.22,
      depth: 23.37,
    },
    warrantyInformation: '3 months warranty',
    shippingInformation: 'Ships in 1-2 business days',
    availabilityStatus: 'Out of Stock',
    reviews: [
      {
        rating: 2,
        comment: 'Would not recommend!',
        date: '2024-05-23T08:56:21.626Z',
        reviewerName: 'Lucas Ramirez',
        reviewerEmail: 'lucas.ramirez@x.dummyjson.com',
      },
      {
        rating: 4,
        comment: 'Fast shipping!',
        date: '2024-05-23T08:56:21.626Z',
        reviewerName: 'Chloe Roberts',
        reviewerEmail: 'chloe.roberts@x.dummyjson.com',
      },
      {
        rating: 3,
        comment: 'Not as described!',
        date: '2024-05-23T08:56:21.626Z',
        reviewerName: 'Benjamin Foster',
        reviewerEmail: 'benjamin.foster@x.dummyjson.com',
      },
    ],
    returnPolicy: '60 days return policy',
    minimumOrderQuantity: 1,
    meta: {
      createdAt: '2024-05-23T08:56:21.626Z',
      updatedAt: '2024-05-23T08:56:21.626Z',
      barcode: '1952499482706',
      qrCode: 'https://assets.dummyjson.com/public/qr-code.png',
    },
    images: [
      'https://cdn.dummyjson.com/products/images/tablets/Samsung%20Galaxy%20Tab%20White/1.png',
      'https://cdn.dummyjson.com/products/images/tablets/Samsung%20Galaxy%20Tab%20White/2.png',
      'https://cdn.dummyjson.com/products/images/tablets/Samsung%20Galaxy%20Tab%20White/3.png',
      'https://cdn.dummyjson.com/products/images/tablets/Samsung%20Galaxy%20Tab%20White/4.png',
    ],
    thumbnail:
      'https://cdn.dummyjson.com/products/images/tablets/Samsung%20Galaxy%20Tab%20White/thumbnail.png',
  },
];
